export const source = [
  {"id": 1, "statement": "Love-themed song"},
  {"id": 2, "statement": "Sequins everywhere"},
  {"id": 3, "statement": "Key change alert"},
  {"id": 4, "statement": "Neighbor voting"},
  {"id": 5, "statement": "Wind machine in use"},
  {"id": 6, "statement": "Epic costume change"},
  {"id": 7, "statement": "Fireworks on stage"},
  {"id": 8, "statement": "Unusual instrument"},
  {"id": 9, "statement": "Dance routine"},
  {"id": 10, "statement": "Fake snow or rain"},
  {"id": 11, "statement": "Synchronized choreography"},
  {"id": 12, "statement": "National flag visible"},
  {"id": 13, "statement": "In-ear monitor malfunction"},
  {"id": 14, "statement": "Audience sing-along"},
  {"id": 15, "statement": "Artist makes a speech"},
  {"id": 16, "statement": "Unexpected language switch"},
  {"id": 17, "statement": "High note performance"},
  {"id": 18, "statement": "Eurovision logo displayed"},
  {"id": 19, "statement": "Song with a message"},
  {"id": 20, "statement": "Retro-themed performance"},
  {"id": 21, "statement": "Epic hair moment"},
  {"id": 22, "statement": "Fog or mist on stage"},
  {"id": 23, "statement": "Crowd wave caught on camera"},
  {"id": 24, "statement": "Pyrotechnics surprise"},
  {"id": 25, "statement": "Rapper on stage"},
  {"id": 26, "statement": "Unexpected dance break"},
  {"id": 27, "statement": "Barefoot performance"},
  {"id": 28, "statement": "Giant prop on stage"},
  {"id": 29, "statement": "Traditional costume"},
  {"id": 30, "statement": "Dramatic lighting change"},
  {"id": 31, "statement": "Controversial staging choice"},
  {"id": 32, "statement": "Artist interacts with audience"},
  {"id": 33, "statement": "Spotlight on backup dancers"},
  {"id": 34, "statement": "Glow-in-the-dark performance"},
  {"id": 35, "statement": "Whistle note in the song"},
  {"id": 36, "statement": "Ethnic instrument featured"},
  {"id": 37, "statement": "Confetti explosion"},
  {"id": 38, "statement": "Artist wears sunglasses"},
  {"id": 39, "statement": "Funky choreography"},
  {"id": 40, "statement": "Political statement made"},
  {"id": 41, "statement": "Unusual stage prop"},
  {"id": 42, "statement": "Water feature on stage"},
  {"id": 43, "statement": "Artist goes barefoot"},
  {"id": 44, "statement": "Confetti canon used"},
  {"id": 45, "statement": "Costume change mid-song"},
  {"id": 46, "statement": "Audience participation moment"},
  {"id": 47, "statement": "Spotlight on backup singers"},
  {"id": 48, "statement": "Stage smoke effects"},
  {"id": 49, "statement": "Artist wears a hat"},
  {"id": 50, "statement": "Unexpected dance style"},
  {"id": 51, "statement": "Dance in slow motion"},
  {"id": 52, "statement": "Unique vocal technique"},
  {"id": 53, "statement": "Virtual background used"},
  {"id": 54, "statement": "Flashing lights on stage"},
  {"id": 55, "statement": "Artist plays an instrument"},
  {"id": 56, "statement": "Retro dance moves"},
  {"id": 57, "statement": "Wind machine hair moment"},
  {"id": 58, "statement": "Group formation change"},
  {"id": 59, "statement": "Use of sign language"},
  {"id": 60, "statement": "Audience dance cam"},
  {"id": 61, "statement": "Contestant wears gloves"},
  {"id": 62, "statement": "Rainbow-colored lights"},
  {"id": 63, "statement": "Dramatic camera angles"},
  {"id": 64, "statement": "Outfit inspired by culture"},
  {"id": 65, "statement": "Audience member waving flag"},
  {"id": 66, "statement": "Handheld camera shot"},
  {"id": 67, "statement": "Interactive LED floor"},
  {"id": 68, "statement": "Artist interacts with camera"},
  {"id": 69, "statement": "Traditional dance featured"},
  {"id": 70, "statement": "Artist jumps on stage"},
  {"id": 71, "statement": "Shirtless male performer"},
  {"id": 72, "statement": "Artist wears high heels"},
  {"id": 73, "statement": "Epic guitar solo"},
  {"id": 74, "statement": "Contestant wears a crown"},
  {"id": 75, "statement": "Audience sings the chorus"},
  {"id": 76, "statement": "Backup dancers in suits"},
  {"id": 77, "statement": "Whistle note in the song"},
  {"id": 78, "statement": "Artist points to the sky"},
  {"id": 79, "statement": "Smoke machine in use"},
  {"id": 80, "statement": "Audience cheers loudly"},
  {"id": 81, "statement": "Artist sings in falsetto"},
  {"id": 82, "statement": "Use of a violin in the song"},
  {"id": 83, "statement": "Audience clapping along"},
  {"id": 84, "statement": "Use of a wind instrument"},
  {"id": 85, "statement": "Contestant wears a mask"},
  {"id": 86, "statement": "Epic dance break"},
  {"id": 87, "statement": "Artist wears a cape"},
  {"id": 88, "statement": "Audience wave in slow motion"},
  {"id": 89, "statement": "Contestant plays air guitar"},
  {"id": 90, "statement": "Artist throws something to crowd"},
  {"id": 91, "statement": "Unique hairstyle on stage"},
  {"id": 92, "statement": "Artist sings with eyes closed"},
  {"id": 93, "statement": "Use of a trumpet in the song"},
  {"id": 94, "statement": "Contestant wears all black"},
  {"id": 95, "statement": "Audience standing ovation"},
  {"id": 96, "statement": "Artist does a spin on stage"},
  {"id": 97, "statement": "Backdrop changes dramatically"},
  {"id": 98, "statement": "Contestant has a hat trick"},
  {"id": 99, "statement": "Audience smartphone lights"},
  {"id": 100, "statement": "Contestant wears sunglasses"}
]
